apiVersion: v1
kind: Pod
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  containers:
    - name: fastapi
      image: fastapi:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
        - containerPort: 5000
          name: http
