version: '3'

services:
  user:
    build: ./user/
    container_name: user
    ports:
      - 5000:5000
    restart: always

  fastapi:
    build: ./feedback/
    container_name: feedback
    ports:
      - 5001:5001
    restart: always

